name: Python Tests

on:
  push:
    branches: [ main, feature/tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pytest
        pip install streamlit

    - name: Run tests
      run: |
        pytest test_app.py
